### ISSUE TITLE
Improve LESS and CSS, test branding branch

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#132]
This issue is to improve LESS code to make use of variables.
@ricardobaeta please add any other things that need to be reviewed, or that you need assistance with.

**Comment by ricardobaeta** [comment]
Thanks @carlosms @smacker for this issue. Other than what you described, I don't have that much to add. The variables defined in `custom-brand.less` get overwritten somehow.

**Comment by dpordomingo** [comment]
not a prio for next R6-CE, will resume next week

**Comment by marnovo** [comment]
Check https://github.com/src-d/sourced-ui/pull/139#issuecomment-506677370

**Comment by dpordomingo** [comment]
> The variables defined in `custom-brand.less` get overwritten somehow. If I redefine `@font-size-base:` for instance, it gets overwritten and I have to declare it on each element.
Variables in less are [lazily defined](http://lesscss.org/features/#variables-feature-lazy-loading), and we have:

```less
superset.less   <<-- entrypoint
  @imports index.less
  @imports vars.less

index.less
  @imports vars.less
  @imports override.less

vars.less
  @brandColor: red

override.less
  @brandColor: blue
  body {
    color: @brandColor
  }
```

When `superset.less` is compiled into `superset.css`, it will appear as it follows:


what would be equivalent to:
```less
superset.less
  @brandColor: red
  @brandColor: blue
  body {
    color: @brandColor
  }
  @brandColor: red
```

so since vars are defined twice (the second one at the end), that one wins, so no override is done:
```css
superset.css
  body {
    color: red
  }
```
